### ISSUE TITLE
Mascot

### ISSUE THREAD

**Issue by jeffclam** [cpe305/fall2016-project-jeffclam#4]
Classes involved:
- Mood.java
- Mascot.java

Please add functionality for Mascot.java in chooseFace(Mood mood) that will return the file location of the corresponding emotion.  Do this with Mood's isNegative() method.

Check if it works in Client.java by making an instance of Mascot and calling chooseFace(mood).

**Comment by jeffclam** [comment]
If you don't have MongoDB installed, you have to comment out all the lines with "database" in them to run the Client.java.

**Comment by R3xKyle-CP** [comment]
In order to add chooseFace(Mood mood), updateFace() and getFace() would both need to take in a mood as a parameter and also then would change Gui.java
